# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: polin_sini
      POSTGRES_PASSWORD: 0000
    volumes:
      - devops_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  devops_db_data:

networks:
  default:
    driver: bridge
